### ISSUE TITLE
NameError: name 'padding' is not defined

### ISSUE THREAD

**Issue by farzinghanbari** [wantinghuang/tensorflow-lstmcrf-postagger#1]
train step has an error!
you haven't defined padding in model_LSTMCRF.py and model_BLSTMCRF.py, here is a part of what I get when I run python train.py:

```
build new model
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    train(flag, os.path.join(data_dir, file_to_save_model), data_dir)
  File "train.py", line 82, in train
    testinputs, testlabels, testseq_length = tagger.pre_process(X_test, y_test)
  File "/home/farzin/tensorflow-lstmcrf-postagger/module/model_LSTMCRF.py", line 113, in pre_process
    inputs.append(padding(data,self.n_inputs,self.max_step))
NameError: name 'padding' is not defined
```

**Comment by jvence** [comment]
Same here.

**Comment by jvence** [comment]
Add the following to your modelXXX.py file:
`    def padding(self,data,per_size,max_step):
        # data is a list with length of sentance size, originally 2d
        zeros = [0.0 for i in range(per_size)]
        try:
            pad = [x.tolist() for x in data] # turn word embedding array to list
        except:
            pad = data.copy()
        if len(data) < max_step:
            while (len(pad) < max_step):
                pad.append(zeros)
        elif len(data) > max_step:
            pad = pad[:max_step]
            #print('input exceeds max_step!')
        else:
            pass
        #print(len(pad))
        return pad`

and update:
            `inputs.append(self.padding(data,self.n_inputs,self.max_step))
            labels.append(self.padding(label,self.n_classes,self.max_step))`
